title:              Blog JTarle
email:              test@gmail.com
description:        Machine Learning Developer
author:             Juan M. Tarletta
baseurl:            "jtarletta.github.io"
url:                "https://Jtarletta.github.io"
root:               /octo-5

# Social Profiles
twitter_username:   
github_username:    JTarletta
facebook_username:  
instagram_username: JTarletta
linkedin_username: 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
